# NUMPY

In [2]:
import numpy as np

In [3]:
#creating array using list
a=np.array([1,2,3,4,5,6])

In [4]:
a

array([1, 2, 3, 4, 5, 6])

In [5]:
#creating array using tuple
a1=np.array((1,2,3,4,5))

In [6]:
a1

array([1, 2, 3, 4, 5])

In [7]:
a.shape

(6,)

In [8]:
a1.shape

(5,)

In [9]:
type(a)

numpy.ndarray

In [10]:
type(a1)

numpy.ndarray

In [11]:
t_d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [12]:
t_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
t_d.shape

(3, 4)

In [14]:
#accessing elements of 1-D array

In [15]:
a[0]

1

In [16]:
a[-1]

6

In [17]:
#slicing elements in 1-D array

In [18]:
a[2:5]

array([3, 4, 5])

In [19]:
a[-2:-1]

array([5])

In [20]:
a[-3:-1]

array([4, 5])

In [21]:
a[-4:-1]

array([3, 4, 5])

In [22]:
a[:5]

array([1, 2, 3, 4, 5])

In [23]:
a[2:]

array([3, 4, 5, 6])

In [47]:
marks=np.array([1,2,3,4,5,6,7,8,9,10])

In [49]:
marks[:5]

array([1, 2, 3, 4, 5])

In [53]:
marks[5:]

array([ 6,  7,  8,  9, 10])

In [55]:
marks[-4:-2]

array([7, 8])

In [57]:
#creating 2-D array

In [61]:
t_d= np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [63]:
t_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
t_d.shape

(3, 4)

In [67]:
t_d[0][1]

2

In [69]:
t_d[0][1:3]

array([2, 3])

In [71]:
a2=np.array(((1,2,3),(4,5,6)))

In [73]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
a2[0][1]

2